version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Running integration tests
      - mvn test-compile failsafe:integration-test failsafe:verify
  post_build:
    commands:
      - echo Build completed on `date`